#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "metronome"
name = "Metronome"
description.en = "A lightweight XMPP server with advanced microblogging features."
description.fr = "Un serveur XMPP léger avec des fonctionnalités avancées de microblogging"

version = "4.0.4~ynh1"

maintainers = []

[upstream]
license = "ISC"
website = "https://archon.im/metronome-im/"
admindoc = "https://archon.im/metronome-im/documentation/"
code = "https://github.com/maranda/metronome"

[integration]
yunohost = ">= 12.0"
architectures = "all"
multi_instance = false
ldap = true
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]

    [resources.sources.main]
    url = "https://github.com/maranda/metronome/archive/refs/tags/v4.0.4.tar.gz"
    sha256 = "e0c1b7043c416dddde198377be61a86438fad29a9bf132717ca17690d3341c74"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]

    [resources.ports]
    client.default = 5222
    server.default = 5269
    client.fixed = true
    server.fixed = true
    client.exposed = true
    server.exposed = true
    http.default = 5290

    [resources.apt]
    packages = [
        "make",
        "gcc",
        "git",
        "lua5.3",
        "liblua5.3-dev",
        "lua5.3-socket",
        "lua5.3-expat",
        "lua5.3-filesystem",
        "lua5.3-dbi-mysql",
        "lua5.3-dbi-postgresql",
        "lua5.3-dbi-sqlite3",
        "lua5.3-sec",
        "libidn11-dev",
        "libssl-dev",
        "lua-event",
        "lua-event-dev",
        "lua-zlib",
        "lua-zlib-dev",
        "lua-ldap",
    ]
