packaging_format = 2

id = "metronome"
name = "Metronome"

description.en = "A lightweight XMPP server with advanced microblogging features."
description.fr = "Un serveur XMPP léger avec des fonctionnalités avancées de microblogging"

version = "4.0.3~ynh1"

maintainers = []

[upstream]
license = "ISC"
website = "https://archon.im/metronome-im/"
admindoc = "https://archon.im/metronome-im/documentation/"
code = "https://github.com/maranda/metronome"

[integration]
yunohost = ">= 12.0"
architectures = "all"
multi_instance = false
ldap = true
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]
        
    [resources.sources.main]
    url = "https://github.com/maranda/metronome/archive/refs/tags/v4.0.3.tar.gz"
    sha256 = "594ff7ebf15c38a73559c9ac6b5cd010b6c5aa8ed28ab68d5530ce0eb07bf81c"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]
    client.default = 5222
    server.default = 5269
    client.fixed = true
    server.fixed = true
    client.exposed = true
    server.exposed = true
    http.default = 5290

    [resources.permissions]

    [resources.apt]
    packages = "make git lua5.3 liblua5.3-dev lua5.3-socket lua5.3-expat lua5.3-filesystem lua5.3-dbi-mysql lua5.3-dbi-postgresql lua5.3-dbi-sqlite3 lua5.3-sec libidn11-dev libssl-dev lua-event lua-event-dev lua-zlib lua-zlib-dev lua-ldap"
