#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/sources"

#=================================================
# BUILD
#=================================================
ynh_script_progression "Building Metronome..."

_build_metronome

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:$app" "$install_dir"
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Configuring Metronome..."

# Add YunoHost modules (are all those really needed ? Could just ldap2 ?)
cp ../conf/modules/* "$install_dir/modules/"

mkdir -p "$install_dir/conf/conf.d"
chmod 700 "$install_dir/conf" "$install_dir/conf/conf.d"
chown -R "$app:root" "$install_dir/conf"

ynh_config_add --template="metronome.cfg.lua" --destination="$install_dir/conf/metronome.cfg.lua"
ynh_config_add --template="domain.cfg.lua" --destination="$install_dir/conf/conf.d/domain.cfg.lua"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring Nginx for muc and xmpp-upload domains..."

# nginx needs read access to metronome files for HTTP upload
_metronome_nginx_read_permissions

cp -R "../conf/hook_conf_regen" "/usr/share/yunohost/hooks/conf_regen/98-nginx_$app"
yunohost tools regen-conf nginx

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Metronome needs access to yunohost ssl certs
usermod -a -G ssl-cert "$app"

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log" --needs_exposed_ports $port_client $port_server

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
touch "/var/log/$app/$app.log"
touch "/var/log/$app/$app.err"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "/var/log/$app"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "/var/log/$app"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:$app" "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"  --wait_until="Hello and welcome to Metronome"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
