#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir/sources"

#=================================================
# BUILD
#=================================================
ynh_script_progression --message="Building Metronome..."

_build_metronome

chmod 750 "$install_dir"
chown -R "$app:$app" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Metronome..."

# Add YunoHost modules (are all those really needed ? Could just ldap2 ?)
cp ../conf/modules/* "$install_dir/modules/"

mkdir -p "$install_dir/conf/conf.d"
chmod 700 "$install_dir/conf" "$install_dir/conf/conf.d"
chown -R "$app:root" "$install_dir/conf"

ynh_add_config --template="metronome.cfg.lua" --destination="$install_dir/conf/metronome.cfg.lua"
ynh_add_config --template="domain.cfg.lua" --destination="$install_dir/conf/conf.d/domain.cfg.lua"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression --message="Configuring Nginx for muc and xmpp-upload domains..."

cp -R "../conf/hook_conf_regen" "/usr/share/yunohost/hooks/conf_regen/98-nginx_$app"
yunohost tools regen-conf nginx

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Metronome needs access to yunohost ssl certs
usermod -a -G ssl-cert "$app"

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add "$app" --log="/var/log/$app/$app.log" --needs_exposed_ports $port_client $port_server

# Use logrotate to manage application logfile(s)
ynh_use_logrotate
touch "/var/log/$app/$app.log"
touch "/var/log/$app/$app.err"
chmod 750 "/var/log/$app"
chmod -R o-rwx "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..."

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log" --line_match="Hello and welcome to Metronome"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
