#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# BUILD
#=================================================
ynh_script_progression --message="Building Metronome..."

builddir="$(mktemp -d)"
ynh_setup_source --dest_dir="$builddir"

pushd "$builddir"
    cp docker/config.unix ./
    make generate_log.install send_mail.install install \
        DESTDIR=$install_dir \
        BIN=$install_dir/bin \
        CONFIG=$install_dir/conf \
        MODULES=$install_dir/modules \
        SOURCE=$install_dir/lib \
        DATA=$data_dir \
        INSTALLEDCONFIG=$install_dir/conf \
        INSTALLEDMODULES=$install_dir/modules \
        INSTALLEDSOURCE=$install_dir/lib \
        INSTALLEDDATA=$data_dir
popd

chmod 750 "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression --message="Configuring Nginx for muc and xmpp-upload domains..."

cp -R ../conf/hook_conf_regen /usr/share/yunohost/hooks/conf_regen/98-nginx_$app
yunohost tools regen-conf nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Metronome..."

# Add YunoHost modules (are all those really needed ? Could just ldap2 ?)
cp ../conf/modules/* $install_dir/modules/

# Metronome needs access to yunohost ssl certs
usermod -a -G ssl-cert $app

mkdir -p $install_dir/conf
chmod 700 $install_dir/conf
chown $app:root $install_dir/conf

ynh_add_config --template="metronome.cfg.lua" --destination="$install_dir/conf/metronome.cfg.lua"
ynh_add_config --template="domain.cfg.lua" --destination="$install_dir/conf/domain.cfg.lua"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..."

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..."

mkdir -p "/var/log/$app"
chmod 750 "/var/log/$app"
chmod -R o-rwx "/var/log/$app"
chown -R $app:$app "/var/log/$app"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service add $app --log="/var/log/$app/$app.log" --needs_exposed_ports $port_client $port_server

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log" --line_match="Hello and welcome to Metronome"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
