#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the install directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring Nginx for muc and xmpp-upload domains..."

# nginx needs read access to metronome files for HTTP upload
_metronome_nginx_read_permissions

cp -R "$YNH_APP_BASEDIR/conf/hook_conf_regen" "/usr/share/yunohost/hooks/conf_regen/98-nginx_$app"
yunohost tools regen-conf nginx

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

# Metronome needs access to yunohost ssl certs
usermod -a -G ssl-cert "$app"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --log="/var/log/$app/$app.log" --needs_exposed_ports $port_client $port_server

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/var/log/$app/"
chmod 750 "/var/log/$app"
chmod -R o-rwx "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading $app's service..."

ynh_systemctl --service="$app" --action="start"  --wait_until="Hello and welcome to Metronome"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
