#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DISABLE METRONOME
#=================================================
# ynh_script_progression --message="Disabling Metronome..."

# if systemctl list-unit-files metronome.service &>/dev/null
# then
# 	ynh_systemd_action --service_name="metronome" --action="stop"
# 	systemctl disable metronome.service --quiet
# fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping $app's systemd service..."

ynh_systemd_action --service_name="$app" --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

if [ -f "$install_dir/conf/domain.cfg.lua" ]; then
    mkdir -p "$install_dir/conf/conf.d"
    mv "$install_dir/conf/domain.cfg.lua" "$install_dir/conf/conf.d/domain.cfg.lua"
    ynh_delete_file_checksum --file="$install_dir/conf/domain.cfg.lua"
    ynh_store_file_checksum --file="$install_dir/conf/conf.d/domain.cfg.lua"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir/sources" --full_replace=1

#=================================================
# BUILD
#=================================================

ynh_script_progression --message="Building Metronome..."

# Back up the conf dir
mv "$install_dir/conf" "$install_dir/conf_bkp"
_build_metronome

ynh_secure_remove --file="$install_dir/conf"
cp -r "$install_dir/conf_bkp" "$install_dir/conf"

chmod 750 "$install_dir"
chown -R "$app:$app" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Metronome..."

# Add YunoHost modules (are all those really needed ? Could just ldap2 ?)
cp ../conf/modules/* "$install_dir/modules/"

mkdir -p $install_dir/conf/conf.d
chmod 700 "$install_dir/conf" "$install_dir/conf/conf.d"
chown -R "$app:root" "$install_dir/conf"

ynh_add_config --template="metronome.cfg.lua" --destination="$install_dir/conf/metronome.cfg.lua"
ynh_add_config --template="domain.cfg.lua" --destination="$install_dir/conf/conf.d/domain.cfg.lua"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression --message="Configuring Nginx for muc and xmpp-upload domains..."

# nginx needs read access to metronome files for HTTP upload
_metronome_nginx_read_permissions

cp -R "../conf/hook_conf_regen" "/usr/share/yunohost/hooks/conf_regen/98-nginx_$app"
yunohost tools regen-conf nginx

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Metronome needs access to yunohost ssl certs
usermod -a -G ssl-cert "$app"

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add "$app" --log="/var/log/$app/$app.log" --needs_exposed_ports $port_client $port_server

# Use logrotate to manage app-specific logfile(s)
ynh_use_logrotate --non-append
chmod 750 "/var/log/$app"
chmod -R o-rwx "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..."

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log" --line_match="Hello and welcome to Metronome"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed"
