#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# DISABLE METRONOME
#=================================================
# ynh_script_progression --message="Disabling Metronome..."

# if systemctl list-unit-files metronome.service &>/dev/null
# then
# 	ynh_systemd_action --service_name="metronome" --action="stop"
# 	systemctl disable metronome.service --quiet
# fi

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..."

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# BUILD METRONOME
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Building Metronome..."

    builddir="$(mktemp -d)"
    ynh_setup_source --dest_dir="$builddir"

    cp -r $install_dir/conf $builddir/conf_bkp
    ynh_secure_remove --file="$install_dir"
    mkdir -p "$install_dir"

    pushd "$builddir"
        cp docker/config.unix ./
        make generate_log.install send_mail.install install \
            DESTDIR=$install_dir \
            BIN=$install_dir/bin \
            CONFIG=$install_dir/conf \
            MODULES=$install_dir/modules \
            SOURCE=$install_dir/lib \
            DATA=$data_dir \
            INSTALLEDCONFIG=$install_dir/conf \
            INSTALLEDMODULES=$install_dir/modules \
            INSTALLEDSOURCE=$install_dir/lib \
            INSTALLEDDATA=$data_dir
    popd

    cp -r $builddir/conf_bkp $install_dir/conf

	ynh_secure_remove --file="$builddir"
fi

chmod 750 "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression --message="Configuring Nginx for muc and xmpp-upload domains..."

cp -R ../conf/hook_conf_regen /usr/share/yunohost/hooks/conf_regen/98-nginx_$app
yunohost tools regen-conf nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Metronome..."

# Add YunoHost modules (are all those really needed ? Could just ldap2 ?)
cp ../conf/modules/* $install_dir/modules/

# Metronome needs access to yunohost ssl certs
usermod -a -G ssl-cert $app

mkdir -p $install_dir/conf
chmod 700 $install_dir/conf
chown $app:root $install_dir/conf

ynh_add_config --template="metronome.cfg.lua" --destination="$install_dir/conf/metronome.cfg.lua"
ynh_add_config --template="domain.cfg.lua" --destination="$install_dir/conf/domain.cfg.lua"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..."

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Upgrading logrotate configuration..."

mkdir -p "/var/log/$app"
chmod 750 "/var/log/$app"
chmod -R o-rwx "/var/log/$app"
chown -R $app:adm "/var/log/$app"

# Use logrotate to manage app-specific logfile(s)
ynh_use_logrotate --non-append

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service add $app --log="/var/log/$app/$app.log" --needs_exposed_ports $port_client $port_server

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log" --line_match="Hello and welcome to Metronome"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed"
